sudo: required
services:
  - docker

test:
  - go get github.com/go-telegram-bot-api/telegram-bot-api
  - go get github.com/tidwall/gjson
  - go get github.com/stretchr/testify/assert
  - env APP_ID=$APP_ID APP_KEY=$APP_KEY go test

after_success:
  - docker build -t realsidsun/oxford-dict-bot .
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push realsidsun/oxford-dict-bot