version: '3.7'

services:
    redis:
        image: redis:7-alpine
    bot:
        # image: realsidsun/oxford-dict-bot:latest
        build: .
        env_file: dev.env
        depends_on:
            - redis
        